// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-01-17 21:30:31
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// News is the golang structure of table news for DAO operations like Where/Data.
type News struct {
	g.Meta     `orm:"table:news, do:true"`
	Id         interface{}
	Title      interface{}
	Content    interface{}
	CreateTime *gtime.Time
}
